---
name: Release - Build and Test

on:
  release:
    types: [published]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"
      - name: Install app dependencies
        run: sudo sh set-up-dependencies.sh
        working-directory: ./api
      - name: Build
        run: go build -v ./...
        working-directory: ./api
      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic -v ./...
        working-directory: ./api
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./api/coverage.out
          flags: api
          fail_ci_if_error: true
          verbose: true
      - name: Test imap client
        run: python3 -m unittest discover -s ./imap-client
        working-directory: ./api

  test-desktop:
    runs-on: ubuntu-latest
    env:
      GH_PACKAGE_READ_TOKEN_DESKTOP: ${{ secrets.GH_PACKAGE_READ_TOKEN_DESKTOP }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.18.0"
      - name: Install dependencies
        run: npm ci --verbose
        working-directory: ./desktop
      - name: Run tests
        run: npm run test:ci
        working-directory: ./desktop
      - name: Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: desktop/coverage/receipt-wrangler-desktop/cobertura-coverage.xml
          format: markdown
          output: both
          badge: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./desktop/coverage/receipt-wrangler-desktop/cobertura-coverage.xml
          flags: desktop
          fail_ci_if_error: true

  build-and-push-docker:
    needs: [test-api, test-desktop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get build date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build and push ARM64
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          platforms: linux/arm64
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/receipt-wrangler:${{ github.ref_name }}-arm64
          build-args: |
            VERSION=${{ github.ref_name }}
            BUILD_DATE=${{ steps.date.outputs.date }}

      - name: Build and push AMD64
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          platforms: linux/amd64
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/receipt-wrangler:${{ github.ref_name }}-amd64
          build-args: |
            VERSION=${{ github.ref_name }}
            BUILD_DATE=${{ steps.date.outputs.date }}

      - name: Create Multi-Arch Manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: ${{ secrets.DOCKER_USERNAME }}/receipt-wrangler:${{ github.ref_name }}
          sources: |
            ${{ secrets.DOCKER_USERNAME }}/receipt-wrangler:${{ github.ref_name }}-amd64
            ${{ secrets.DOCKER_USERNAME }}/receipt-wrangler:${{ github.ref_name }}-arm64

      - name: Cleanup Architecture-Specific Tags
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: |
          TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"username\": \"${DOCKER_USERNAME}\", \"password\": \"${DOCKER_TOKEN}\"}" \
            https://hub.docker.com/v2/users/login/ | jq -r .token)

          curl -X DELETE \
            -H "Authorization: Bearer ${TOKEN}" \
            "https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/receipt-wrangler/tags/${VERSION}-amd64/"

          curl -X DELETE \
            -H "Authorization: Bearer ${TOKEN}" \
            "https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/receipt-wrangler/tags/${VERSION}-arm64/"
